version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      #Listener OUTSIDE userà la porta 9093 per le connessioni esterne.
      #Listener INSIDE userà la porta 9092 per i container Docker.
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://172.30.241.168:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs:1:1"
    volumes:
      - kafka-data:/kafka/data  # Volume per i dati di Kafka
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    ports:
      - "9000:9000"  # Porta per accedere a Kafka Manager
    environment:
      - ZK_HOSTS=zookeeper:2181  # Indirizzo di Zookeeper
      - KAFKA_VERSION=2.13-2.8.1 # versione di Kafka
      - KM_VERSION=latest  # Versione di Kafka Manager
    depends_on:
      - zookeeper
      - kafka

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data  # Volume per i dati di Elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - kafka
      - elasticsearch

  lcs_test:
    build:
      context: .
      dockerfile: Dockerfile
    image: lcs_test
    ports:
      - "8080:8080"
    env_file:
      - project-school-config-local.envfile
    restart: always

volumes:
  kafka-data:
  elasticsearch-data: